version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - ${DOCKER_NGINX_80}:80
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/api/config/nginx:/etc/nginx/conf.d
    depends_on:
      - api
  api:
    image: kanaheijoy/php7.3:latest
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${DOCKER_MYSQL_3306}:3306
    command:
      - --innodb-buffer-pool-size=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
